version: '3.9'

services:
  postgres-instance:
    image: postgres:13.6-bullseye
    restart: always
    container_name: postgres-instance
    hostname: postgres-instance
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: my_pass
      POSTGRES_USER: my_user
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    networks:
      - crocobet

  hazelcast:
    image: hazelcast/hazelcast:5.0
    container_name: hazelcast
    ports:
      - "5701:5701"
    networks:
      - crocobet

  hazelcast-mgmt:
    image: hazelcast/management-center:latest
    container_name: hazelcast-mgmt
    ports:
      - "48080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
    networks:
      - crocobet

  spring-boot-user-management-service:
    container_name: user-mngmnt-container
    hostname: user-management-service
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/user_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_pass
      AUTH_SECRET_KEY: secreto
      HAZELCAST_HOST: hazelcast
      HAZELCAST_PORT: 5701
    depends_on:
      - postgres-instance
      - hazelcast
    networks:
      - crocobet

networks:
  crocobet:
    driver: bridge

