version: '3.9'

services:
  postgres-instance:
    image: postgres:13.6-bullseye
    restart: always
    container_name: postgres-instance
    hostname: postgres-instance
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: my_pass
      POSTGRES_USER: my_user
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"

  hazelcast:
    image: hazelcast/hazelcast
    container_name: hazelcast
    ports:
      - "5701:5701"
    networks:
      - hazelcast-net

  hazelcast-mgmt:
      image: hazelcast/management-center:latest
      container_name: hazelcast-mgmt
      ports:
        - "48080:8080"
      environment:
        - MC_DEFAULT_CLUSTER=dev
        - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
      networks:
        - hazelcast-net

networks:
  hazelcast-net:
    driver: bridge